# Generated by Django 5.2.2 on 2025-06-09 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название блока')),
            ],
            options={
                'verbose_name': 'Блок вопросов',
                'verbose_name_plural': 'Блоки вопросов',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(blank=True, max_length=255, verbose_name='Название блока (для импорта)')),
                ('type', models.CharField(choices=[('closed', 'Закрытый'), ('multiclosed', 'Множественный выбор'), ('open', 'Открытый'), ('pairs', 'Соответствия')], max_length=20, verbose_name='Тип вопроса')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Баллы')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.block', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название теста')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timer', models.PositiveIntegerField(default=30, verbose_name='Таймер (минуты)')),
                ('codepass', models.CharField(blank=True, default='', max_length=255, verbose_name='Код доступа')),
                ('questions', models.ManyToManyField(blank=True, related_name='tests', to='quiz.question', verbose_name='Вопросы')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='TestBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_questions', models.PositiveIntegerField(default=1, verbose_name='Количество вопросов из блока')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.block')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.test')),
            ],
            options={
                'verbose_name': 'Блок в тесте',
                'verbose_name_plural': 'Блоки в тесте',
                'unique_together': {('test', 'block')},
            },
        ),
        migrations.AddField(
            model_name='test',
            name='blocks',
            field=models.ManyToManyField(blank=True, related_name='tests', through='quiz.TestBlock', to='quiz.block', verbose_name='Блоки'),
        ),
    ]
