# Generated by Django 5.2.2 on 2025-06-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_competence_discipline_question_competence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='competences',
            field=models.ManyToManyField(blank=True, related_name='tests', to='quiz.competence', verbose_name='Компетенции (для генерации)'),
        ),
        migrations.AddField(
            model_name='test',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='tests', to='quiz.discipline', verbose_name='Дисциплины (для генерации)'),
        ),
    ]
