# Generated by Django 5.2.2 on 2025-06-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_test_competences_test_disciplines'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='closed_score',
            field=models.FloatField(default=0, verbose_name='Баллы за закрытые вопросы'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='open_score',
            field=models.FloatField(default=0, verbose_name='Баллы за открытые вопросы'),
        ),
    ]
