# Generated by Django 5.2.2 on 2025-06-23 15:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_testresult_closed_score_testresult_open_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=ckeditor.fields.RichTextField(verbose_name='Вопрос'),
        ),
    ]
